name: 'Setup dependencies'
description: 'Setup dependencies'
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: "11"
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2