name: 'Matrix value in composite action Test'
description: 'testing'
runs:
  using: "composite"
  steps:
    - run: echo ${{ matrix.flavor }}
      shell: bash

    - run: echo ${{ secrets.GITHUB_TOKEN }}
      shell: bash