on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3

      - name: Setup dependencies
        #uses: ./.github/actions/setup
        uses: chizoba/setup-action@master

      - id: foo
        uses: ./.github/actions/composite-action-demo
        with:
          who-to-greet: 'Chizoba'
#      - run: echo random-number ${{ steps.foo.outputs.random-number }}
#        shell: bash
